let medias = require('../data/medias.json');

module.exports = () => {
    return {
        getTitles: () => {
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            // ...
            return medias
        }
    }
}